version: '3'
services:
  frontend:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: your-backend-api-image
    ports:
      - "5000:5000"
